
---
- name: Install Git Create image and run conteiners
  hosts: all
  become: yes
  ignore_errors: yes

  tasks:
  - name: Check and Print LINUX system
    debug: var=ansible_distribution

  - block:   #============Dlock for Ubuntu=============
    - name: Install Git
      shell: "apt-get install git"

    - name: Download Dockerfile from GitHub
      shell: "git clone https://github.com/Alex8Efremov/AnsibleDocker.git"

    - name: Install Docker image
      command: "docker build -t dockerimage:v1 ."
      args:
        chdir: "/home/ubuntu/AnsibleDocker/"
    when: ansible_distribution == "Ubuntu"

  - block:    #===================Block for RedHat=====================
    - name: Install Git RedHat
      shell: "yum install git -y"

    - name: Download Dockerfile from GitHub
      shell: "git clone https://github.com/Alex8Efremov/AnsibleDocker.git"

    - name: Install Docker Image
      command: "docker build -t dockerimage:v1 ."
      args:
        chdir: "/home/ec2-user/AnsibleDocker/"
    when: ansible_distribution == "RedHat"

  - name: Check Containers
    shell: "docker ps -aq"
    register: resul

  - name: Delete containers
    shell: "{{ item }}"
    with_items:
        - docker stop $(docker ps -q)
        - docker rm $(docker ps -a -q)
    when: resul.stdout_lines[0] != False

  - name: Create Container
    shell: "docker run -d -p {{ item }}:80 dockerimage:v1"
    with_items: ['7777', '8888', '9999', '9998']

  - debug:
      var: resul.stdout_lines
